### ISSUE TITLE
Add the SD and SR diagrams

### ISSUE THREAD

**Issue by WidmarO** [WidmarO/Testigos-del-bitcoin-T2#1]
- [x] Upload the SD and SR diagrams, overwrite the existing files.

**Comment by Marko99-CC** [comment]
Diagrama SD y SR elaborada satisfactoriamente usando las metodologías aprendidas con i*.

**Comment by Marko99-CC** [comment]
Diagrama SD-STutoría-Fijo4 y SR-STutoría-Fijo6 elaborada satisfactoriamente usando las metodologías aprendidas con i*.
